encyclopedia/urls.py
from django.urls import path

from . import views


app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:item>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("newpage/", views.newpage, name="newpage"),
    path("edit/<str:item>", views.editpage, name="editpage"),
    path("randompage/", views.randompage, name="randompage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.shortcuts import render, redirect
import markdown2
import random

from . import util

# Form to create new wiki page
class CreatePageForm(forms.Form):
    title = forms.CharField(label="Title", max_length=100)
    content = forms.CharField(label="Markdown Content", widget=forms.Textarea)

# Form for editing page
class EditPageForm(forms.Form):
    content = forms.CharField(label="", widget=forms.Textarea)
    

def entry(request, item):
    # error if page doesn't exist
    if util.get_entry(item) == None:
        return render(request, "encyclopedia/error.html", {
            "item": item
        })
    # load page with title and content
    return render(request, "encyclopedia/item.html", {
    "content": markdown2.markdown(util.get_entry(item)),
    "item": item
    })
 

def search(request):
    if request.method == "POST":
        item = request.POST.get('q')
        if  util.get_entry(item):
            return render(request, "encyclopedia/item.html", {
            "content": markdown2.markdown(util.get_entry(item)),
            "item": item
            })
        else:
            matches = []
            entries = util.list_entries()
            for entry in entries:
                if item.lower() in entry.lower():
                    matches.append(entry)
            return render(request, "encyclopedia/search.html", {
                "matches": matches,
                "item": item
            })

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def newpage(request):
    
    valid = True
    duplicate = False
    
    if request.method == "POST":
        # pull form input
        form = CreatePageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            content = "#" + title + "\n \n" + content 
            print(title)
            print("............................................")
            print(content)
            # check if page with same title exists
            if util.get_entry(title) == None:
                util.save_entry(title, content)
                return entry(request, title)
            else:
                duplicate = True
                return render(request, "encyclopedia/newpage.html", {
                    "form": form,
                    "duplicate": duplicate,
                    "title": title
                })
        # if form input is invalid
        else:
            valid = False
            return render(request, "encyclopedia/newpage.html", {
                "form": form,
                "valid": valid
            })

    return render(request, "encyclopedia/newpage.html", {
        "form": CreatePageForm
    })

def editpage(request, item):
    valid = True
    if request.method == "POST":
        # pull form input
        form = EditPageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(item, content)
            return entry(request, item)
        # if form input is invalid
        else:
            valid = False
            return render(request, "encyclopedia/editpage.html", {
                "form": form,
                "valid": valid
            })

    raw_content = util.get_entry(item)
    form = EditPageForm({"content": raw_content})
    return render(request, "encyclopedia/editpage.html", {
        "form": form,
        "title": item
    })

def randompage(request):
    entries = util.list_entries()
    length = len(entries)
    num = random.randint(0, length - 1)
    entry = entries[num]
    return render(request, "encyclopedia/item.html", {
        "item": entry,
        "content": markdown2.markdown(util.get_entry(entry))
    })

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    <br>
    {% if valid == False %}
        <h3>Input is invalid!</h3>
    {% endif %}
    <form action="{% url 'encyclopedia:editpage' item=title %}" method="post">
        {% csrf_token %}
        <div>{{ form }}</div>
        <input type="submit" value="Save Page">
    </form>  
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error!
{% endblock %}

{% block body %}
    <h1>Error!</h1>
    <p>No such entry for {{ item }}</p>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="/wiki/{{ entry }}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/item.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ item }}
{% endblock %}

{% block body %}
    <div>
        {{ content|safe }}
    </div>
    <a href="/edit/{{ item }}">Edit this Page</a>
{% endblock %}


encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Jeff's Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}

    <h1>Create a New Wiki Page</h1>
    <br>
    {% if valid == False %}
        <h3>Input is invalid!</h3>
    {% elif duplicate == True %}
        <h3>Page with title '{{ title }}' already exists!</h3>
    {% endif %}

    <form action="{% url 'encyclopedia:newpage' %}" method="post">
        {% csrf_token %}
        <div>
            {{ form }}
        </div>
        <input type="submit" value="Save Page">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search Results for '{{ item }}'</h1>
    <br>
    <ul>
        {% for match in matches %}
            <li>
                <a href="/wiki/{{ match }}">{{ match }}</a>
            </li>
            {% empty %}
                <h3>No results found!</h3>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/test.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>This is a test</title>
    </head>
    <body>
        <h1>This is a test!</h1>
    </body>
</html>